apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: order-service
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  strategy: {}
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - image: numpyh/order-service:v1.4
        name: order-service
        ports:
        - containerPort: 30001
        livenessProbe:
          tcpSocket:
            port: 30001
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 30001
          initialDelaySeconds: 20
          periodSeconds: 10
        resources: 
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"
        envFrom:
        - secretRef:
            name: order-service-secret
status: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-service
  name: order-service
spec:
  ports:
  - name: 30001-30001
    port: 30001
    protocol: TCP
    targetPort: 30001
  selector:
    app: order-service
  type: ClusterIP
status:
  loadBalancer: {}
