services:
  broker_service:
    container_name: broker_service
    build:
      context: ../broker
      dockerfile: ../broker/Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - user_service
    env_file:
      - ../broker/.env

  user_service:
    container_name: user_service
    build:
      context: ../user
      dockerfile: ../user/Dockerfile
    ports:
      - "50001:50001"
    restart: always
    depends_on:
      - postgres
    env_file:
      - ../user/.env

  product_service:
    container_name: product_service
    build:
      context: ../product
      dockerfile: ../product/Dockerfile
    ports:
      - "40001:40001"
    restart: always
    depends_on:
      - postgres
    env_file:
      - ../product/.env

  order_service:
    container_name: order_service
    build:
      context: ../order
      dockerfile: ../order/Dockerfile
    ports:
      - "30001:30001"
    restart: always
    depends_on:
      - postgres
    env_file:
      - ../order/.env
  
  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../user/.env

volumes:
  postgres_data: