apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: broker-service
  name: broker-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker-service
  strategy: {}
  template:
    metadata:
      labels:
        app: broker-service
    spec:
      containers:
      - image: numpyh/broker-service:v1.2
        name: broker-service
        resources: 
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        envFrom:
        - secretRef:
            name: broker-service-secret
status: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: broker-service
  name: broker-service
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: broker-service
  type: NodePort
status:
  loadBalancer: {}
